In [1]:
# Import libraries
import pandas as pd
import openpyxl
from ydata_profiling import ProfileReport

### Importing Datasets

In [2]:
df_item = pd.read_csv("C:/Users/Jeffs/Documents/PADS Insper/3T/order_items.csv")
df_reviews = pd.read_csv("C:/Users/Jeffs/Documents/PADS Insper/3T/order_reviews.csv")
df_orders = pd.read_csv("C:/Users/Jeffs/Documents/PADS Insper/3T/orders.csv")
df_products = pd.read_csv("C:/Users/Jeffs/Documents/PADS Insper/3T/products.csv")
df_geolocation = pd.read_csv("C:/Users/Jeffs/Documents/PADS Insper/3T/geolocation.csv")
df_sellers = pd.read_csv("C:/Users/Jeffs/Documents/PADS Insper/3T/sellers.csv")
df_order_pay = pd.read_csv("C:/Users/Jeffs/Documents/PADS Insper/3T/order_payments.csv")
df_customers = pd.read_csv("C:/Users/Jeffs/Documents/PADS Insper/3T/customers.csv")
df_category = pd.read_csv("C:/Users/Jeffs/Documents/PADS Insper/3T/product_category_name_translation.csv")

### Merging Datasets

In [7]:
df_olist = df_orders.merge(df_item, on='order_id', how='left')
df_olist = df_olist.merge(df_order_pay, on='order_id', how='outer', validate='m:m')
df_olist = df_olist.merge(df_reviews, on='order_id', how='outer')
df_olist = df_olist.merge(df_products, on='product_id', how='outer')
df_olist = df_olist.merge(df_customers, on='customer_id', how='outer')
df_olist = df_olist.merge(df_sellers, on='seller_id', how='outer')
# sem geolocation
#  df_olist = df_olist.merge(df_customers, on='zip_code_prefix', how='outer')

print(df_olist.shape)

(119143, 39)

In [8]:
# Produce and save the profiling report
profile = ProfileReport(df_olist,title="Olist profile")
profile.to_file("report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
df_olist.head(5) # To display the top 5 rows 
df_olist.tail(5)  # To display the botton 5 rows

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state
119138,1ab38815794efa43d269d62b98dae815,a0b67404d84a70ef420a7f99ad6b190a,delivered,2018-07-01 10:23:10,2018-07-05 16:17:52,2018-07-04 14:34:00,2018-07-09 15:06:57,2018-07-20 00:00:00,1.0,31ec3a565e06de4bdf9d2a511b822b4d,...,30.0,28.0,28.0,2077f7ec37df79c62cc24b7b8f30e8c9,8528,ferraz de vasconcelos,SP,13660.0,porto ferreira,SP
119139,b159d0ce7cd881052da94fa165617b05,e0c3bc5ce0836b975d6b2a8ce7bb0e3e,canceled,2017-03-11 19:51:36,2017-03-11 19:51:36,NaN,NaN,2017-03-30 00:00:00,1.0,241a1ffc9cf969b27de6e72301020268,...,16.0,4.0,11.0,78a159045124eb7601951b917a42034f,89111,gaspar,SC,89031.0,blumenau,SC
119140,735dce2d574afe8eb87e80a3d6229c48,d531d01affc2c55769f6b9ed410d8d3c,delivered,2018-07-24 09:46:27,2018-07-24 11:24:27,2018-07-24 15:14:00,2018-08-02 22:47:35,2018-08-16 00:00:00,1.0,1d187e8e7a30417fda31e85679d96f0f,...,80.0,8.0,30.0,8cf3c6e1d2c8afaab2eda3fa01d4e3d2,60455,fortaleza,CE,13478.0,americana,SP
119141,25d2bfa43663a23586afd12f15b542e7,9d8c06734fde9823ace11a4b5929b5a7,delivered,2018-05-22 21:13:21,2018-05-22 21:35:40,2018-05-24 12:28:00,2018-06-12 23:11:29,2018-06-08 00:00:00,1.0,6e1c2008dea1929b9b6c27fa01381e90,...,41.0,21.0,41.0,e55e436481078787e32349cee9febf5e,39803,teofilo otoni,MG,8320.0,sao paulo,SP
119142,1565f22aa9452ff278638e87cc895678,56772dfbcbe7df908a284ff0d53adf7d,delivered,2018-05-15 17:41:00,2018-05-16 03:35:29,2018-05-16 17:20:00,2018-05-21 14:31:41,2018-05-29 00:00:00,1.0,9c1e194db1d35a79d962ea610bfe0868,...,17.0,8.0,13.0,6ceea7c1088e15ab3c67980a2d9bb309,9687,sao bernardo do campo,SP,14092.0,ribeirao preto,SP

In [9]:
#Quantas linhas e colunas (variáveis) estão contidas no dataset?
# identificar o volume de dados do DataFrame: 
# shape[0] = #registros
# shape[1] = #variáveis

print("# Registros:\t{}".format(df_olist.shape[0]))
print("# Variáveis:\t{}\n".format(df_olist.shape[1])) 

#Quais os tipos das variáveis?
display(df_olist.dtypes)

# Registros:	119143
# Variáveis:	39

order_id                          object
customer_id                       object
order_status                      object
order_purchase_timestamp          object
order_approved_at                 object
order_delivered_carrier_date      object
order_delivered_customer_date     object
order_estimated_delivery_date     object
order_item_id                    float64
product_id                        object
seller_id                         object
shipping_limit_date               object
price                            float64
freight_value                    float64
payment_sequential               float64
payment_type                      object
payment_installments             float64
payment_value                    float64
review_id                         object
review_score                     float64
review_comment_title              object
review_comment_message            object
review_creation_date              object
review_answer_timestamp           object
product_category_name             object
product_name_lenght              float64
product_description_lenght       float64
product_photos_qty               float64
product_weight_g                 float64
product_length_cm                float64
product_height_cm                float64
product_width_cm                 float64
customer_unique_id                object
customer_zip_code_prefix           int64
customer_city                     object
customer_state                    object
seller_zip_code_prefix           float64
seller_city                       object
seller_state                      object
dtype: object

In [10]:
df_olist.shape #total de linhas, total de colunas

(119143, 39)

In [11]:
df_olist.count() # contar qty de linhas em cada coluna

order_id                         119143
customer_id                      119143
order_status                     119143
order_purchase_timestamp         119143
order_approved_at                118966
order_delivered_carrier_date     117057
order_delivered_customer_date    115722
order_estimated_delivery_date    119143
order_item_id                    118310
product_id                       118310
seller_id                        118310
shipping_limit_date              118310
price                            118310
freight_value                    118310
payment_sequential               119140
payment_type                     119140
payment_installments             119140
payment_value                    119140
review_id                        118146
review_score                     118146
review_comment_title              13989
review_comment_message            50245
review_creation_date             118146
review_answer_timestamp          118146
product_category_name            116601
product_name_lenght              116601
product_description_lenght       116601
product_photos_qty               116601
product_weight_g                 118290
product_length_cm                118290
product_height_cm                118290
product_width_cm                 118290
customer_unique_id               119143
customer_zip_code_prefix         119143
customer_city                    119143
customer_state                   119143
seller_zip_code_prefix           118310
seller_city                      118310
seller_state                     118310
dtype: int64

In [10]:
duplicate_rows_df = df_olist[df_olist.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape) #total de linhas duplicadas

number of duplicate rows:  (0, 39)

In [11]:
df_olist = df_olist.drop_duplicates() #removendo os dados duplicados (se houver)
df_olist.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,19.0,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350.0,maua,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,19.0,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350.0,maua,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,19.0,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350.0,maua,SP
3,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,delivered,2017-08-15 18:29:31,2017-08-15 20:05:16,2017-08-17 15:28:33,2017-08-18 14:44:43,2017-08-28 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,19.0,8.0,13.0,3a51803cc0d012c3b5dc8b7528cb05f7,3366,sao paulo,SP,9350.0,maua,SP
4,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,delivered,2017-08-02 18:24:47,2017-08-02 18:43:15,2017-08-04 17:35:43,2017-08-07 18:30:01,2017-08-15 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,19.0,8.0,13.0,ef0996a1a279c26e7ecbd737be23d235,2290,sao paulo,SP,9350.0,maua,SP

In [12]:
df_olist.describe(include='all') #dados gerais do seu df
df_olist.describe() #dados gerais do seu df

,order_item_id,price,freight_value,payment_sequential,payment_installments,payment_value,review_score,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_zip_code_prefix,seller_zip_code_prefix
count,118310.000000,118310.000000,118310.000000,119140.000000,119140.000000,119140.000000,118146.000000,116601.000000,116601.000000,116601.000000,118290.000000,118290.000000,118290.000000,118290.000000,119143.000000,118310.000000
mean,1.196543,120.646603,20.032387,1.094737,2.941246,172.735135,4.015582,48.767498,785.967822,2.205161,2112.250740,30.265145,16.619706,23.074799,35033.451298,24442.410413
std,0.699489,184.109691,15.836850,0.730141,2.777848,267.776077,1.400436,10.033540,652.584121,1.717452,3786.695111,16.189367,13.453584,11.749139,29823.198969,27573.004511
min,1.000000,0.850000,0.000000,1.000000,0.000000,0.000000,1.000000,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000,1003.000000,1001.000000
25%,1.000000,39.900000,13.080000,1.000000,1.000000,60.850000,4.000000,42.000000,346.000000,1.000000,300.000000,18.000000,8.000000,15.000000,11250.000000,6429.000000
50%,1.000000,74.900000,16.280000,1.000000,2.000000,108.160000,5.000000,52.000000,600.000000,1.000000,700.000000,25.000000,13.000000,20.000000,24240.000000,13660.000000
75%,1.000000,134.900000,21.180000,1.000000,4.000000,189.240000,5.000000,57.000000,983.000000,3.000000,1800.000000,38.000000,20.000000,30.000000,58475.000000,27972.000000
max,21.000000,6735.000000,409.680000,29.000000,24.000000,13664.080000,5.000000,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000,99990.000000,99730.000000

## Limpando

In [14]:
print(df_olist.isnull().sum())

order_id                              0
customer_id                           0
order_status                          0
order_purchase_timestamp              0
order_approved_at                   177
order_delivered_carrier_date       2086
order_delivered_customer_date      3421
order_estimated_delivery_date         0
order_item_id                       833
product_id                          833
seller_id                           833
shipping_limit_date                 833
price                               833
freight_value                       833
payment_sequential                    3
payment_type                          3
payment_installments                  3
payment_value                         3
review_id                           997
review_score                        997
review_comment_title             105154
review_comment_message            68898
review_creation_date                997
review_answer_timestamp             997
product_category_name              2542
product_name_lenght                2542
product_description_lenght         2542
product_photos_qty                 2542
product_weight_g                    853
product_length_cm                   853
product_height_cm                   853
product_width_cm                    853
customer_unique_id                    0
customer_zip_code_prefix              0
customer_city                         0
customer_state                        0
seller_zip_code_prefix              833
seller_city                         833
seller_state                        833
dtype: int64